import pandas as pd
from datetime import datetime, timedelta
import random

def generate_sample_data():
    """Generate sample data that matches the actual Jira structure exactly."""
    
    # Actual ticket data from your Jira system
    sample_tickets = [
        # Epic: CX-2 - OptumCDO
        {
            'ticket_id': 'CX-2',
            'parent': '',
            'summary': 'OptumCDO',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 13),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 0,
            'is_parent': True
        },
        # Children of CX-2
        {
            'ticket_id': 'CX-107',
            'parent': 'CX-2',
            'summary': 'MBR July',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 28),
            'due_date': datetime(2025, 7, 28),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-108',
            'parent': 'CX-2',
            'summary': 'MBR August',
            'status': 'TO DO',
            'start_date': datetime(2025, 8, 25),
            'due_date': datetime(2025, 8, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-109',
            'parent': 'CX-2',
            'summary': 'QBR Sept',
            'status': 'TO DO',
            'start_date': datetime(2025, 9, 29),
            'due_date': datetime(2025, 9, 29),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-110',
            'parent': 'CX-2',
            'summary': 'MBR Oct',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-127',
            'parent': 'CX-2',
            'summary': 'Tag Based Row Filter Support',
            'status': 'TO DO',
            'start_date': datetime(2025, 10, 31),
            'due_date': datetime(2025, 10, 31),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-128',
            'parent': 'CX-2',
            'summary': 'Purpose Based Policy Support',
            'status': 'TO DO',
            'start_date': datetime(2025, 12, 31),
            'due_date': datetime(2025, 12, 31),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-129',
            'parent': 'CX-2',
            'summary': 'MVP Completion',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 23),
            'due_date': datetime(2025, 12, 31),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-130',
            'parent': 'CX-2',
            'summary': 'Data Product 1 Onboarding',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 22),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-131',
            'parent': 'CX-2',
            'summary': 'Data Product 2 Onboarding',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 22),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-132',
            'parent': 'CX-2',
            'summary': 'Data Product 3 Onboarding',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 22),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-17',
            'parent': 'CX-2',
            'summary': 'Blue Use Case Onboarding',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 13),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-18',
            'parent': 'CX-2',
            'summary': 'Databricks Firewalling',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 13),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-19',
            'parent': 'CX-2',
            'summary': 'Kick off Workshop',
            'status': 'Done',
            'start_date': datetime(2025, 6, 17),
            'due_date': datetime(2025, 6, 18),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-22',
            'parent': 'CX-2',
            'summary': 'Quick Start',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 23),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': True
        },
        
        # CX-44 - Child of CX-22
        {
            'ticket_id': 'CX-44',
            'parent': 'CX-22',
            'summary': 'SOW-OptumQuickStart',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 23),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 2,
            'is_parent': True
        },
        
        # Children of CX-44
        {
            'ticket_id': 'CX-45',
            'parent': 'CX-44',
            'summary': 'Onboarding & Kick Off',
            'status': 'Done',
            'start_date': datetime(2025, 6, 16),
            'due_date': datetime(2025, 6, 16),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-51',
            'parent': 'CX-44',
            'summary': 'Architecture and Design Review',
            'status': 'Done',
            'start_date': datetime(2025, 6, 16),
            'due_date': datetime(2025, 6, 18),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-53',
            'parent': 'CX-44',
            'summary': 'Use Case Review and Acceptance Sign Off',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 16),
            'due_date': datetime(2025, 6, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-54',
            'parent': 'CX-44',
            'summary': 'Enablement and User Training',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 23),
            'due_date': datetime(2025, 7, 11),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-64',
            'parent': 'CX-44',
            'summary': 'Dev Activation',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 23),
            'due_date': datetime(2025, 6, 27),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-67',
            'parent': 'CX-44',
            'summary': 'Go Live',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 7),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-68',
            'parent': 'CX-44',
            'summary': 'Engagement Closure and Handover',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 18),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-69',
            'parent': 'CX-44',
            'summary': 'UAT Activation',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 23),
            'due_date': datetime(2025, 7, 3),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        {
            'ticket_id': 'CX-77',
            'parent': 'CX-44',
            'summary': 'Prod Activation',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 3,
            'is_parent': True
        },
        
        # Epic: CX-7 - OptumServe
        {
            'ticket_id': 'CX-7',
            'parent': '',
            'summary': 'OptumServe',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 1),
            'due_date': datetime(2025, 8, 1),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 0,
            'is_parent': True
        },
        # Children of CX-7
        {
            'ticket_id': 'CX-157',
            'parent': 'CX-7',
            'summary': 'Demo of CI/CD using github actions',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 7),
            'due_date': datetime(2025, 8, 1),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-158',
            'parent': 'CX-7',
            'summary': 'Demo of PrivaceraDiscovery',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 7),
            'due_date': datetime(2025, 8, 1),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-159',
            'parent': 'CX-7',
            'summary': 'Demo of S3 FileServer and API client',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 7),
            'due_date': datetime(2025, 8, 1),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-160',
            'parent': 'CX-7',
            'summary': 'Training to new joinees',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 7),
            'due_date': datetime(2025, 8, 1),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-161',
            'parent': 'CX-7',
            'summary': 'HA/DR configuration',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 7),
            'due_date': datetime(2025, 8, 1),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-23',
            'parent': 'CX-7',
            'summary': 'FIPS certification',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 1),
            'due_date': datetime(2025, 7, 30),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 1,
            'is_parent': False
        },
        
        # Epic: CX-149 - OptumInsights
        {
            'ticket_id': 'CX-149',
            'parent': '',
            'summary': 'OptumInsights',
            'status': 'TO DO',
            'start_date': datetime(2025, 7, 4),
            'due_date': None,
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 0,
            'is_parent': False
        }
    ]
    
    # Add all the missing children tickets with proper hierarchy levels
    additional_tickets = [
        # Children of CX-45
        {
            'ticket_id': 'CX-46',
            'parent': 'CX-45',
            'summary': 'KickOff',
            'status': 'Done',
            'start_date': datetime(2025, 6, 16),
            'due_date': datetime(2025, 6, 16),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-47',
            'parent': 'CX-45',
            'summary': 'Org, BU and Dev Tenant Creation',
            'status': 'Done',
            'start_date': datetime(2025, 6, 16),
            'due_date': datetime(2025, 6, 16),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-58',
            'parent': 'CX-45',
            'summary': 'Support Onboarding',
            'status': 'Done',
            'start_date': datetime(2025, 6, 16),
            'due_date': datetime(2025, 6, 16),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        # Child of CX-51
        {
            'ticket_id': 'CX-52',
            'parent': 'CX-51',
            'summary': 'Deployment Architecture',
            'status': 'In Progress',
            'start_date': datetime(2025, 6, 16),
            'due_date': datetime(2025, 6, 16),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        
        # Children of CX-53
        {
            'ticket_id': 'CX-59',
            'parent': 'CX-53',
            'summary': 'Use Case 1',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-60',
            'parent': 'CX-53',
            'summary': 'Use Case 2',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        
        # Children of CX-54
        {
            'ticket_id': 'CX-104',
            'parent': 'CX-54',
            'summary': 'Administrator Training',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 11),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-105',
            'parent': 'CX-54',
            'summary': 'End User Training',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 11),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        
        # Children of CX-64
        {
            'ticket_id': 'CX-137',
            'parent': 'CX-64',
            'summary': 'Acceptance: 7 - TBAC access',
            'status': 'In Progress',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 7, 9),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-143',
            'parent': 'CX-64',
            'summary': 'Integration - Usersync',
            'status': 'In Progress',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 6, 27),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-144',
            'parent': 'CX-64',
            'summary': 'Acceptance: 2 - RBAC column masking',
            'status': 'Done',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 6, 27),
            'rag': 'Green',
            'comments': 'Sanjeev Karani: Tested successfully in customer dev environment',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-145',
            'parent': 'CX-64',
            'summary': 'Acceptance: 3 - RBAC row filtering',
            'status': 'In Progress',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 6, 27),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-146',
            'parent': 'CX-64',
            'summary': 'Acceptance: 5 - ABAC column masking',
            'status': 'In Progress',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 6, 27),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-147',
            'parent': 'CX-64',
            'summary': 'Acceptance: 6 - ABAC row filtering',
            'status': 'In Progress',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 6, 27),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-148',
            'parent': 'CX-64',
            'summary': 'Acceptance: 8 - TBAC column masking',
            'status': 'In Progress',
            'start_date': datetime(2025, 7, 3),
            'due_date': datetime(2025, 6, 27),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-48',
            'parent': 'CX-64',
            'summary': 'Privacera Platform Install',
            'status': 'Done',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 23),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-49',
            'parent': 'CX-64',
            'summary': 'Integration - Snowflake',
            'status': 'Done',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 3),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-50',
            'parent': 'CX-64',
            'summary': 'CI/CD(GitHubs Action) Automation',
            'status': 'Done',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 23),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-55',
            'parent': 'CX-64',
            'summary': 'Diagnostics Setup and Proactive Alerting',
            'status': 'In Progress',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 24),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-57',
            'parent': 'CX-64',
            'summary': 'Integration - SSO',
            'status': 'In Progress',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 23),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-61',
            'parent': 'CX-64',
            'summary': 'Completion and Sign Off',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 11),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-85',
            'parent': 'CX-64',
            'summary': 'Pre-Requisites Available',
            'status': 'Done',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 23),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-86',
            'parent': 'CX-64',
            'summary': 'Pre-req Questionnaire Shared',
            'status': 'Done',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 23),
            'rag': 'Green',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-91',
            'parent': 'CX-64',
            'summary': 'Acceptance: 1- RBAC access',
            'status': 'Done',
            'start_date': datetime(2025, 7, 7),
            'due_date': datetime(2025, 7, 7),
            'rag': 'Green',
            'comments': 'Sanjeev Karani: Tested successfully in customer dev environment',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-92',
            'parent': 'CX-64',
            'summary': 'Acceptance: 4 - ABAC access',
            'status': 'In Progress',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 8),
            'rag': 'Amber',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        
        # Children of CX-67
        {
            'ticket_id': 'CX-100',
            'parent': 'CX-67',
            'summary': 'Go Live Sign off',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-101',
            'parent': 'CX-67',
            'summary': 'Implementation',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-102',
            'parent': 'CX-67',
            'summary': 'Celebration!',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-97',
            'parent': 'CX-67',
            'summary': 'Acceptance: 1',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-98',
            'parent': 'CX-67',
            'summary': 'Acceptance: 2',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-99',
            'parent': 'CX-67',
            'summary': 'Readiness',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        
        # Children of CX-68
        {
            'ticket_id': 'CX-103',
            'parent': 'CX-68',
            'summary': 'Run books sign off',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        
        # Children of CX-69
        {
            'ticket_id': 'CX-70',
            'parent': 'CX-69',
            'summary': 'Privacera Platform Install',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 30),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-71',
            'parent': 'CX-69',
            'summary': 'Integration - Snowflake',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 30),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-72',
            'parent': 'CX-69',
            'summary': 'CI/CD(GitHubs Action) Automation',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 30),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-73',
            'parent': 'CX-69',
            'summary': 'Diagnostics Setup and Proactive Alerting',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 1),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-75',
            'parent': 'CX-69',
            'summary': 'Integration - SSO',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 30),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-76',
            'parent': 'CX-69',
            'summary': 'Completion and Sign Off',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 3),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-87',
            'parent': 'CX-69',
            'summary': 'Pre-req Questionnaire Shared',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-88',
            'parent': 'CX-69',
            'summary': 'Pre-req Available',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 6, 25),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-93',
            'parent': 'CX-69',
            'summary': 'Acceptance: 1',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 17),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-94',
            'parent': 'CX-69',
            'summary': 'Acceptance: 2',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        
        # Children of CX-77
        {
            'ticket_id': 'CX-78',
            'parent': 'CX-77',
            'summary': 'Privacera Platform Install',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-79',
            'parent': 'CX-77',
            'summary': 'Integration - Snowflake',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-80',
            'parent': 'CX-77',
            'summary': 'CI/CD(GitHubs Action) Automation',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-81',
            'parent': 'CX-77',
            'summary': 'Diagnostics Setup and Proactive Alerting',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-82',
            'parent': 'CX-77',
            'summary': 'Integration - Datahub',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-83',
            'parent': 'CX-77',
            'summary': 'Integration - SSO',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-84',
            'parent': 'CX-77',
            'summary': 'Completion and Sign Off',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-89',
            'parent': 'CX-77',
            'summary': 'Pre-req Questionnaire Shared',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-90',
            'parent': 'CX-77',
            'summary': 'Pre-req Available',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-95',
            'parent': 'CX-77',
            'summary': 'Acceptance: 1',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        },
        {
            'ticket_id': 'CX-96',
            'parent': 'CX-77',
            'summary': 'Acceptance: 2',
            'status': 'TO DO',
            'start_date': datetime(2025, 6, 14),
            'due_date': datetime(2025, 7, 18),
            'rag': '',
            'comments': '',
            'last_updated': datetime(2025, 7, 8, 5, 57, 42),
            'hierarchy_level': 4,
            'is_parent': False
        }
    ]
    
    # Combine all tickets
    all_tickets = sample_tickets + additional_tickets
    
    # Convert to DataFrame
    df = pd.DataFrame(all_tickets)
    
    # Generate summary data based on actual counts
    summary_data = {
        'total_tickets': 86,
        'epics': 3,
        'children': 83,
        'with_dates': {
            'start_date': 86,
            'due_date': 78,
            'both_dates': 78
        },
        'by_status': {
            'TO DO': 63,
            'Done': 13,
            'In Progress': 10
        },
        'by_rag': {
            'Green': 13,
            'Amber': 10,
            'Red': 0
        },
        'with_comments': 2,
        'extraction_timestamp': '2025-07-08T05:57:42.705Z'
    }
    
    return df, summary_data 